name: Advanced Schema Stream CS

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: Image URL
        required: true
        default: "images/ps-finished.png"
      reset_image_url:
        description: Reset Image URL
        required: true
        default: "images/ps-start.png"
      duration:
        description: "Number of job duration in ms"
        required: true
        default: "45000"
      x:
        description: "Number of cells on x-Axis"
        required: true
        default: "16"
      y:
        description: "Number of cells on y-Axis"
        required: true
        default: "12"
      pixel-x:
        description: "Number of pixels on x-Axis"
        required: true
        default: "800"
      pixel-y:
        description: "Number of pixels on y-Axis"
        required: true
        default: "600"
      repetitions:
        description: "Number of matrix cell render cycles"
        required: true
        default: "1"
      repetition-delay:
        description: "Wait time in ms between render cycles"
        required: true
        default: "60000"
      connections-per-cell:
        description: "PlanetScale DB connections per matrix cell"
        required: true
        default: "10"

jobs:
  enter-matrix:
    name: "Render Matrix Cell"
    runs-on: ps-runner

    strategy:
      fail-fast: false
      #max-parallel: 16
      matrix:
        x: [4, 5, 6, 7, 8, 9, 10, 11, 12]
        y: [3, 4, 5, 6, 7, 8, 9, 10]
        include:
          - x: 3
            y: 8
          - x: 3
            y: 9
          - x: 3
            y: 10
          - x: 8
            y: 2
          - x: 8
            y: 11
          - x: 9
            y: 2
          - x: 9
            y: 11
          - x: 13
            y: 3
          - x: 13
            y: 4  
          - x: 14
            y: 2
          - x: 14
            y: 3
        # exclude:
        #   - x: 4
        #     y: [3, 4]
        #   - x: 5
        #     y: [6, 7]
        #   - x: 6
        #     y: [5, 6, 9, 10]
        #   - x: 7
        #     y: [4, 5, 8]
        #   - x: 8
        #     y: [4, 7]
        #   - x: 9
        #     y: [6, 9]
        #   - x: 10
        #     y: [5, 8, 9]
        #   - x: 12
        #     y: [3, 10]
        #   - x: 13
        #     y: [5, 6, 7, 8, 9, 10]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Stream pixels into PlanetScale DB
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: |
          sleep $((RANDOM%5)) # do not start all processes at the very same time
          python3 render-matrix-cell.py --operation PIN --max-x='${{github.event.inputs.pixel-x}}' --max-y='${{github.event.inputs.pixel-y}}' --job-x='${{matrix.x}}' --job-y='${{matrix.y}}' --max-job-x='${{github.event.inputs.x}}' --max-job-y='${{github.event.inputs.y}}' --duration='${{github.event.inputs.duration}}' --environment='${{github.actor}}' --image-file='${{ github.event.inputs.image_url }}' --repetitions '${{github.event.inputs.repetitions}}' --connections '${{github.event.inputs.connections-per-cell}}' --repetition-delay '${{github.event.inputs.repetition-delay}}'
